site_name: Mad-Pascal
site_author: TeBe
site_description: "Mad-Pascal Documentation"

repo_url: https://github.com/tebe6502/mad-pascal-en-mkdocs/
edit_uri: ""

theme:
    name: readthedocs
    hljs_languages:
        - delphi

nav:
    - Introduction: introduction.md
    - Memory map: map.md
    - Usage: usage.md
    - Syntax: syntax.md
    - Types: types.md
    - Constants: constants.md

    - Variables: variables.md
    - Instructions: instructions.md
    - Programs, units, librarys: units.md
    - Procedures, functions, modifiers: procedures-functions.md
    - Macros: macros.md
    - Assembler inlining: asm.md
    - Resource files: resources.md
    - File operations: files.md
    - Interrupt handling: interrupts.md
    - Alternative to DOS: ados.md
    - Essential libraries: essential-libraries.md
    - Tips and tricks: tips.md
    - Examples: examples.md
    - Projects: projects.md
